### PR TITLE
Fixed -e flag option to place output format for files

### LINKED ISSUE #394: Output filename doesn't respect -e flag
**Describe the bug**
When using the `-e` flag to change output format, the default filename remains `input_file + ".svg"`

**To Reproduce**

1.  `mmdc -e pdf -i input.mmd`
2. file produced: `input.mmd.svg
3. file format: pdf

**Expected behavior**
1.  `mmdc -e pdf -i input.mmd`
2. file produced: `input.mmd.pdf`
3. file format: pdf

**Desktop (please complete the following information):**

- OS: Ubunti 22.04
- Browser: N/A
- Version @mermaid-js/mermaid-cli 9.1.7

### PR DESCRIPTION
**Pull request by OmiCoding**
## :bookmark_tabs: Summary

Brief description about the content of your PR.

Fixing  `-e` flag option to place output format to the file.

Resolves #394 

## :straight_ruler: Design Decisions

Describe the way your implementation works or what design decisions you made if applicable.

Added an `if` statement to check if `-e` flag is given. If so then the extension is added to the output file by assigning the `output` variable with the extension specified. Also added additional tests to see if the logic is working. 

## :clipboard: Tasks

Make sure you

- [x] :book: have read the [contribution guidelines](https://github.com/mermaid-js/mermaid-cli/blob/master/CONTRIBUTING.md)
- [x] :computer: have added unit/e2e tests (if appropriate)
- [x] :bookmark: targeted `master` branch

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -98,7 +98,11 @@ async function cli () {
   // if an input file is defined, it should take precedence, otherwise, input is
   // coming from stdin and just name the file out.svg, if it hasn't been
   // specified with the '-o' option
-    output = input ? (input + '.svg') : 'out.svg'
+    if(outputFormat) {
+      output = input ? (input + '.' + outputFormat) : 'out' + '.' + outputFormat
+    } else {
+      output = input ? (input + '.svg') : 'out.svg'
```
Comment (aloisklink) [inline src/index.js:104]: We might as well use [template strings](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals), since this project only supports newer versions of JavaSript.

```suggestion
      output = input ? (`${input}.${outputFormat}`) : `out.${outputFormat}`
    } else {
      output = input ? (`${input}.svg`) : 'out.svg'
```

File: src/index.js [hunk 2]
```diff
@@ -98,7 +98,11 @@ async function cli () {
   // if an input file is defined, it should take precedence, otherwise, input is
   // coming from stdin and just name the file out.svg, if it hasn't been
   // specified with the '-o' option
-    output = input ? (input + '.svg') : 'out.svg'
+    if(outputFormat) {
```
Comment (aloisklink) [inline src/index.js:101]: I think you need to do the following to get the linter happy.

It should be automatically fixed by `yarn run lint-fix` too.

```suggestion
    if (outputFormat) {
```

**Review by aloisklink — CHANGES_REQUESTED** [review]
Thanks for the PR, and for making some great tests!

Everything looks great, we just need to fix the linter issues.
Please run `yarn run lint-fix`, and that should auto-format your code.

**Comment by OmiCoding** [comment]
> Thanks for the PR, and for making some great tests!
> 
> Everything looks great, we just need to fix the linter issues. Please run `yarn run lint-fix`, and that should auto-format your code.

No problem! I set the changes you've suggested! Let me know if I need to make any more changes.

**Review by aloisklink — APPROVED** [review]
Awesome! All CI tests are passing now :)

I'll leave this open for a day or two, in case other maintainers want to review it.

By the way, I've labelled your PR as `hacktoberfest-accepted` in case you're participating in https://hacktoberfest.com/ for the free T-shirt/tree planted.

**Comment by OmiCoding** [comment]
I had forgotten I signed up for that! :joy:

I appreciate that! It was fun making a contribution to this project!
